os: linux
language: node_js

install:
  - npm install -g codecov
  - yarn

node_js:
  - "lts/*"

jobs:
  include:
    - script: yarn build
    - script: yarn test
    - stage: release
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script:
      #   - make
      deploy:
        provider: script
        skip_cleanup: true
        script:
          npx semantic-release
        on:
          all_branches: true
