os: linux
language: node_js

install:
  - npm install -g codecov
  - yarn 

node_js:
  - "lts/*"

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage:   release to master
      script: skip
      if: branch == master
      deploy:
        provider: script
        skip_cleanup: true
        script:
          npx semantic-release

    - name: release to next
      script: skip
      if: branch == next
      deploy:
        provider: script
        skip_cleanup: true
        script:
          npx semantic-release
