os: linux
language: node_js

install:
  - npm install -g codecov
  - yarn 

node_js:
  - "lts/*"

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release to master
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      on:
        branch: master
      deploy:
        provider: script
        skip_cleanup: true
        script:
          npx semantic-release

    - stage: release to next
      on:
        branch: next
      deploy:
        provider: script
        skip_cleanup: true
        script:
          npx semantic-release
