os: linux
language: node_js

install:
  - npm install -g codecov
  - yarn

node_js:
  - "lts/*"

jobs:
  include:
    - stage: build & test
      script:
        - yarn build
        - yarn test
      deploy:
        - provider: pages
          github_token: $GH_TOKEN
          local_dir: docs
          skip_cleanup: true
          on:
            branch: master
        - provider: script
          skip_cleanup: true
          script:
            npx semantic-release
          on:
            all_branches: true
